version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
        #IP:EXTERNAL:INTERNAL
      - 127.0.0.1:8001:80
    links:
      - db
    volumes:
      - ./web:/opt
      - ./log/spring:/var/logs
  db:
    image: mariadb
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./log/mariadb:/var/log/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: database
    ports:
        #IP:EXTERNAL:INTERNAL
      - 127.0.0.1:8002:3306
  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
          #IP:EXTERNAL:INTERNAL
        - 127.0.0.1:8003:80
      links:
        - db
      environment:
        - PMA_HOST=db
